name: whiteboard
description: A package for freehand use on whiteboard. This package provides a cross platform widget for drawing with controller.
version: 0.0.2
homepage: https://github.com/rkishan516/whiteboard

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter